### ISSUE TITLE
Compile using docker

### ISSUE THREAD

**Issue by VictorSigma** [MTG/essentia.js#1]
I realize this is a new project so the documentation is not done yet but I thought I would give it a go. When I try to compile in docker using the below command I get a bunch of unresolved symbol errors. I tried adding ```#include <essentia/debugging.h>``` to ```essentiamin.cpp``` but no luck. I am not familiar with emscripten so any help would be appreciated. 

```

root@c5f24f99030b:/essentia.js# emconfigure sh -c './build-essentia-bindings.sh'

  emconfigure is a helper for configure, setting various environment
  variables so that emcc etc. are used. Typical usage:

    emconfigure ./configure [FLAGS]

  (but you can run any command instead of configure)



Compiling the bindings to bitcode ...

error: unresolved symbol: _ZN8essentia10nameOfTypeERKSt9type_info
error: unresolved symbol: _ZN8essentia12ParameterMap3addERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_9ParameterE
error: unresolved symbol: _ZN8essentia13setDebugLevelEi
error: unresolved symbol: _ZN8essentia15unsetDebugLevelEi
error: unresolved symbol: _ZN8essentia4Pool3addERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS1_6vectorIfNS5_IfEEEEb
error: unresolved symbol: _ZN8essentia4initEv
error: unresolved symbol: _ZN8essentia6Logger5debugENS_15DebuggingModuleERKNSt3__212basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEb
error: unresolved symbol: _ZN8essentia8shutdownEv
error: unresolved symbol: _ZN8essentia8standard9Algorithm5inputERKNSt3__212basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
error: unresolved symbol: _ZN8essentia8standard9Algorithm6outputERKNSt3__212basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
error: unresolved symbol: _ZN8essentia9ParameterD1Ev
error: unresolved symbol: _ZN8essentia14loggerInstanceE
error: unresolved symbol: _ZN8essentia15EssentiaFactoryINS_8standard9AlgorithmEE9_instanceE
error: unresolved symbol: _ZN8essentia15infoLevelActiveE
error: unresolved symbol: _ZN8essentia16debugIndentLevelE
error: unresolved symbol: _ZN8essentia16errorLevelActiveE
error: unresolved symbol: _ZN8essentia18warningLevelActiveE
error: unresolved symbol: _ZN8essentia20activatedDebugLevelsE
error: unresolved symbol: _ZN8essentia8standard9Algorithm14processingModeE
Aborting compilation due to previous errors | undefined
Traceback (most recent call last):
  File "/emscripten/emcc.py", line 3042, in <module>
    sys.exit(run())
  File "/emscripten/emcc.py", line 1759, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/emscripten/tools/shared.py", line 2274, in emscripten
    emscripten._main(cmdline)
  File "/emscripten/emscripten.py", line 2222, in _main
    return temp_files.run_and_clean(lambda: main(
  File "/emscripten/tools/tempfiles.py", line 93, in run_and_clean
    return func()
  File "/emscripten/emscripten.py", line 2227, in <lambda>
    DEBUG=DEBUG,
  File "/emscripten/emscripten.py", line 2153, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/emscripten/emscripten.py", line 86, in emscript
    glue, forwarded_data = compiler_glue(metadata, libraries, compiler_engine, temp_files, DEBUG)
  File "/emscripten/emscripten.py", line 218, in compiler_glue
    glue, forwarded_data = compile_settings(compiler_engine, libraries, temp_files)
  File "/emscripten/emscripten.py", line 530, in compile_settings
    cwd=path_from_root('src'), error_limit=300)
  File "/emscripten/tools/jsrun.py", line 132, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['nodejs', '/emscripten/src/compiler.js', '/tmp/tmpDdWe__.txt', '/emscripten/src/embind/emval.js', '/emscripten/src/embind/embind.js', '/emscripten/src/library_pthread_stub.js'] to finish with return code 0, but it returned with code 1 instead! Output: // The Module object: Our interface to the outside world. We import
// and export values on it. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(Module) { ..generated code.. }
// 3. pre-run appended it, var Module = {}; ..generated
ERROR:root:Configure step failed with non-zero return code: 1.  Command line: sh -c ./build-essentia-bindings.sh at /essentia.js
```

**Comment by albincorreya** [comment]
Hi @VictorSigma, thanks for testing the docker image and reporting. This was mostly due to some existing cache of previous compilation errors of bindings. You can give a try on  `emcc --clear-cache` in future similar occurrences. Made some updates in the bindings and tested rebuilding the wasm modules using docker. It should work as expected now. Let me know if not!
